name: Deploy Backend to AWS ECS

on:
  push:
    branches: [main, develop, dev]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build & Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get Infrastructure Outputs
        run: |
          echo "ECR_REPOSITORY=$(aws cloudformation describe-stacks \
            --stack-name InfraStack \
            --query "Stacks[0].Outputs[?OutputKey=='EcrRepositoryName'].OutputValue" \
            --output text)" >> $GITHUB_ENV

          echo "ECS_CLUSTER=$(aws cloudformation describe-stacks \
            --stack-name InfraStack \
            --query "Stacks[0].Outputs[?OutputKey=='EcsClusterName'].OutputValue" \
            --output text)" >> $GITHUB_ENV

          echo "ECS_SERVICE=$(aws cloudformation describe-stacks \
            --stack-name InfraStack \
            --query "Stacks[0].Outputs[?OutputKey=='EcsServiceName'].OutputValue" \
            --output text)" >> $GITHUB_ENV

      - name: Show Infrastructure
        run: |
          echo "Repository: $ECR_REPOSITORY"
          echo "Cluster: $ECS_CLUSTER"
          echo "Service: $ECS_SERVICE"

      - name: Build, tag and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd backend

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Force ECS Redeployment
        run: |
          aws ecs update-service \
            --cluster "$ECS_CLUSTER" \
            --service "$ECS_SERVICE" \
            --force-new-deployment

      - name: Wait for ECS deployment
        run: |
          aws ecs wait services-stable \
            --cluster "$ECS_CLUSTER" \
            --services "$ECS_SERVICE"

      - name: Deployment completed
        run: |
          echo "✅ Backend deployed successfully"